// runtime/package/lockfile.cpp — rivet.lock read/write/resolve
#include "lockfile.hpp"
#include "../../platform/interface/fs.hpp"

#include <algorithm>
#include <format>
#include <sstream>

namespace rivet::pkg {

// ─── parse_lockfile() ─────────────────────────────────────────────────────────

Result<LockFile> parse_lockfile(const Path& path) {
    auto data = rivet::fs::read_file(path);
    if (!data) return propagate<LockFile>(data);

    std::string_view text(reinterpret_cast<const char*>(data->data()), data->size());
    std::istringstream ss{std::string(text)};
    std::string line;

    LockFile lf;
    LockedDep* current = nullptr;

    while (std::getline(ss, line)) {
        // Strip comments.
        if (auto h = line.find('#'); h != std::string::npos) line = line.substr(0, h);
        while (!line.empty() && std::isspace((unsigned char)line.back())) line.pop_back();
        if (line.empty()) continue;

        if (line == "[[package]]") {
            lf.packages.emplace_back();
            current = &lf.packages.back();
            continue;
        }

        auto eq = line.find('=');
        if (eq == std::string::npos || !current) continue;

        auto key = line.substr(0, eq);
        auto val = line.substr(eq + 1);

        // Trim.
        auto trim = [](std::string& s) {
            while (!s.empty() && std::isspace((unsigned char)s.front())) s.erase(s.begin());
            while (!s.empty() && std::isspace((unsigned char)s.back())) s.pop_back();
            if (s.size() >= 2 && s.front() == '"' && s.back() == '"')
                s = s.substr(1, s.size() - 2);
        };
        trim(key); trim(val);

        if      (key == "name")       current->name       = val;
        else if (key == "version")    current->version    = val;
        else if (key == "source")     current->source     = val;
        else if (key == "checksum")   current->checksum   = val;
        else if (key == "git_url")    current->git_url    = val;
        else if (key == "git_commit") current->git_commit = val;
    }

    return lf;
}

// ─── write_lockfile() ────────────────────────────────────────────────────────

Result<void> write_lockfile(const LockFile& lf, const Path& path) {
    std::string out;
    out += std::format("# This file is auto-generated by rivet. Do not edit manually.\n");
    out += std::format("# rivet.lock format version {}\n\n", lf.format_version);

    // Sort packages alphabetically for stable diffs.
    auto sorted = lf.packages;
    std::sort(sorted.begin(), sorted.end(), [](const LockedDep& a, const LockedDep& b) {
        return a.name < b.name;
    });

    for (const auto& pkg : sorted) {
        out += "[[package]]\n";
        out += std::format("name     = \"{}\"\n",    pkg.name);
        out += std::format("version  = \"{}\"\n",    pkg.version);
        out += std::format("source   = \"{}\"\n",    pkg.source);
        if (!pkg.checksum.empty())
            out += std::format("checksum = \"{}\"\n", pkg.checksum);
        if (!pkg.git_url.empty())
            out += std::format("git_url    = \"{}\"\n", pkg.git_url);
        if (!pkg.git_commit.empty())
            out += std::format("git_commit = \"{}\"\n", pkg.git_commit);
        if (!pkg.deps.empty()) {
            out += "deps = [";
            for (std::size_t i = 0; i < pkg.deps.size(); ++i) {
                if (i) out += ", ";
                out += '"'; out += pkg.deps[i]; out += '"';
            }
            out += "]\n";
        }
        out += "\n";
    }

    return rivet::fs::write_atomic(path,
        rivet::ByteSpan{reinterpret_cast<const std::byte*>(out.data()), out.size()});
}

// ─── resolve() ───────────────────────────────────────────────────────────────

Result<LockFile> resolve(const Manifest& manifest) {
    // Phase 3 will implement PubGrub SAT-based resolution.
    // For now: emit one LockedDep per declared direct dependency using whatever
    // version constraint is specified (no transitive resolution yet).

    LockFile lf;
    lf.root_name    = manifest.name;
    lf.root_version = manifest.version;

    for (const auto& [name, spec] : manifest.dependencies) {
        LockedDep dep;
        dep.name    = name;
        dep.version = spec.version;  // placeholder — real resolver selects exact version
        dep.source  = (spec.kind == DepKind::Git)  ? "git"
                    : (spec.kind == DepKind::Path) ? "path"
                    :                                "registry";
        dep.git_url    = spec.git_url;
        dep.git_commit = spec.git_ref;
        lf.packages.push_back(std::move(dep));
    }

    return lf;
}

// ─── is_up_to_date() ─────────────────────────────────────────────────────────

bool is_up_to_date(const LockFile& lf, const Manifest& manifest) {
    // Lock is stale if any dependency in the manifest is not present in the lock.
    for (const auto& [name, spec] : manifest.dependencies) {
        auto it = std::find_if(lf.packages.begin(), lf.packages.end(),
                               [&](const LockedDep& d) { return d.name == name; });
        if (it == lf.packages.end()) return false;
    }
    return true;
}

} // namespace rivet::pkg
